# Make file targets to build TCP client & TCP server (Assignment 1, problem #3)
# Format
# target: dependencies
#   action

.PHONY: client

all: client

client:
	gcc test_client.c -o client

clean:
	rm client

