# Make file targets to build TCP client & TCP server (Assignment 1, problem #3)
# Format
# target: dependencies
#   action

.PHONY: server

all: server

server:
	gcc tcp_server.c -o server

clean:
	rm server

